version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    container_name: todo_backend
    image: todo_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/todo_db
    env_file:
      - 'backend/.env'
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: ["rails", "server", "-b", "0.0.0.0"]
  
volumes:
  pg_data: