version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_development
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    container_name: todo_backend
    image: todo_backend
    restart: always
    depends_on:
      - db
      - kafka
    env_file:
      - 'backend/.env'
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: sh -c "rm -f /app/tmp/pids/server.pid && bundle exec karafka-web migrate && bundle exec rake db:migrate && bundle exec bin/rails server -p 3000 -b 0.0.0.0"
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: kafka_zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  consumer:
    build: ./backend
    container_name: todo_consumer
    restart: always
    depends_on:
      - kafka
    env_file:
      - 'backend/.env'
    environment:
      KAFKA_BROKER: kafka:9092
    command: ["bundle", "exec", "karafka", "server"]
  
volumes:
  pg_data: